config/routes.rb
Rails.application.routes.draw do
	
  resources :contactforms
  resources :areas
  resources :locations
  resources :categories

  devise_for :users
  resources :users, :only => [:show, :index]

 

  resources :posters do
    member { post :approve }
    member { post :favorite }
  	resources :comments
  end

  root to: "posters#index"
  match 'search', to: 'search#index', via: 'get'
  match 'dashboard', to: 'static_pages#dashboard', via: 'get'
  match 'aboutus', to: 'static_pages#aboutus', via: 'get'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ApplicationRecord
	has_many :connections
	has_many :posters, through: :connections
	belongs_to :location
end

app/models/category.rb
class Category < ApplicationRecord
	belongs_to :user
	has_many :sections
	has_many :posters, through: :sections
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :poster
end

app/models/connection.rb
class Connection < ApplicationRecord
	belongs_to :poster
	belongs_to :area
end

app/models/contactform.rb
class Contactform < ApplicationRecord
end

app/models/location.rb
class Location < ApplicationRecord
	has_many :taggings
	has_many :posters, through: :taggings
	has_many :areas
	geocoded_by :address
    after_validation :geocode, :if => :address_changed?
end

app/models/photo.rb
class Photo < ApplicationRecord
	belongs_to :poster
    mount_uploader :posterimage, PosterimageUploader
end

app/models/poster.rb
class Poster < ApplicationRecord
    
    markable_as :favorite
	belongs_to :user
	has_many :comments
	has_many :sections
    has_many :categories, :through => :sections
    has_many :connections
  has_many :areas, through: :connections
    has_many :taggings
	has_many :locations, :through => :taggings
	has_many :photos
    accepts_nested_attributes_for :photos, :allow_destroy => true
    default_scope -> { order('created_at DESC') }


def all_categories
  self.categories.map(&:name).join(", ")
end

def all_locations
  self.locations.map(&:address).join(", ")
end


end

app/models/section.rb
class Section < ApplicationRecord
	belongs_to :poster
	belongs_to :category
end

app/models/tagging.rb
class Tagging < ApplicationRecord
	belongs_to :poster
	belongs_to :location
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_marker
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posters
  has_many :comments
  has_many :categories
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  before_action :set_area, only: [:show, :edit, :update, :destroy]

  # GET /areas
  # GET /areas.json
  def index
    @areas = Area.all
  end

  # GET /areas/1
  # GET /areas/1.json
  def show
  end

  # GET /areas/new
  def new
    @area = Area.new
    @areas = Area.all
  end

  # GET /areas/1/edit
  def edit
  end

  # POST /areas
  # POST /areas.json
  def create
    @area = Area.new(area_params)

    respond_to do |format|
      if @area.save
        format.html { redirect_to "/areas/new" , notice: 'Area was successfully created.' }
        format.json { render :show, status: :created, location: @area }
      else
        format.html { render :new }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /areas/1
  # PATCH/PUT /areas/1.json
  def update
    respond_to do |format|
      if @area.update(area_params)
        format.html { redirect_to "/areas/new", notice: 'Area was successfully updated.' }
        format.json { render :show, status: :ok, location: @area }
      else
        format.html { render :edit }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /areas/1
  # DELETE /areas/1.json
  def destroy
    @area.destroy
    respond_to do |format|
      format.html { redirect_to "/areas/new", notice: 'Area was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_area
      @area = Area.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def area_params
      params.require(:area).permit(:name, :location_id)
    end
end

app/controllers/posters_controller.rb
class PostersController < ApplicationController
  before_action :set_poster, only: [:show, :edit, :update, :destroy]


  # GET /posters
  # GET /posters.json
  def index
    @posters = Poster.where(approved: true).all
    @categories = Category.all
    @locations = Location.all
  end

  # GET /posters/1
  # GET /posters/1.json
  def show
  end

  # GET /posters/new
  def new
    @poster = Poster.new
    @poster.photos.new
  end

  # GET /posters/1/edit
  def edit
    @poster.photos.new
  end

def approve
  @poster = Poster.find(params[:id])
  @poster.update(approved: true)
  redirect_to "/dashboard"
  flash[:notice] = 'Poster has been approved'
end

  def favorite
  @poster = Poster.find(params[:id])
  current_user.set_mark :favorite, @poster
  flash[:notice] = 'Added to favorites'
   respond_to do |format|
    format.html {redirect_to :back}
      format.js 
    end
end

  # POST /posters
  # POST /posters.json
  def create
    @poster = Poster.new(poster_params)
    @poster.user = current_user
    flash[:notice] = 'Your post has been submitted for review.'
    respond_to do |format|
      if @poster.save
        if params[:photos_attributes]
          params[:photos_attributes].each do |photo|
            @poster.photos.create(posterimage: photo[:posterimage])
          end
        end
        format.html { redirect_to '/', notice: 'Poster was successfully created.' }
        format.json { render :show, status: :created, location: @poster }
      else
        format.html { render :new }
        format.json { render json: @poster.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posters/1
  # PATCH/PUT /posters/1.json
  def update
    respond_to do |format|
      if @poster.update(poster_params)
        if params[:photos_attributes]
          params[:photos_attributes].each do |photo|
            @poster.photos.create(posterimage: photo[:posterimage])
          end
        end
        format.html { redirect_to '/', notice: 'Poster was successfully updated.' }
        format.json { render :show, status: :ok, location: @poster }
      else
        format.html { render :edit }
        format.json { render json: @poster.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posters/1
  # DELETE /posters/1.json
  def destroy
    @poster.destroy
    respond_to do |format|
      format.html { redirect_to '/', notice: 'Poster was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poster
      @poster = Poster.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def poster_params
      params.require(:poster).permit(:title, :description, :company, :place, :phone1, :phone2, :price, :negotiate, :area_ids, :category_ids, :location_ids, :photos_attributes => [:posterimage])
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController


       def index
            q = params[:q]
            @posters = Poster.search(title_or_description_cont: q).result
        end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def show
@user = User.find(params[:id])
@posters = current_user.posters
@favorites = current_user.favorite_posters
end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_class_for flash_type
    case flash_type
      when :success
        "alert-success"
      when :error
        "alert-danger"
      when :alert
        "alert-warning"
      when :notice
        "alert-info"
      else
        flash_type.to_s
    end
  end

end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contactforms_helper.rb
module ContactformsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/posters_helper.rb
module PostersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/areas/_area.html.erb
<tr>
        <td><%= area.name %></td>
        <td><%= area.location.address %></td>
        <td><%= link_to 'Show', area %></td>
        <td><%= link_to 'Edit', edit_area_path(area) %></td>
        <td><%= link_to 'Destroy', area, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>

app/views/areas/_form.html.erb
<%= form_for(area) do |f| %>
  
<div class="container">
  <div class="row">
    <div class="col-md-4 col-md-offset-4 col-xs-12">
  <% if area.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(area.errors.count, "error") %> prohibited this area from being saved:</h2>

      <ul>
      <% area.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 

    <div class="form-group">
      <label>Select Region:</label>
     <br>
       <%= f.collection_select :location_id, Location.all, :id, :address, {prompt: "Choose Region"}, 
    {class: "selectpicker"} %>
   <br>
  </div>
 <div class="form-group">
    <label>Area name:</label>
    <%= f.text_field :name, :class => "form-control" %>
  </div>

 
  <br>

  <div class="actions">
    <%= f.submit "New area", :class => "btn btn-primary" %>
  </div>
<% end %>


  <br>
  <br>

</div>
</div>
</div>

<script type="text/javascript">

$( document ).ready(function() {
 
 $('.selectpicker').selectpicker({
  size: 4
});

});


</script>

app/views/areas/edit.html.erb
<h1>Editing Area</h1>

<%= render 'form', area: @area %>

<%= link_to 'Show', @area %> |
<%= link_to 'Back', areas_path %>

app/views/areas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Areas</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @areas.each do |area| %>
      <tr>
        <td><%= area.name %></td>
        <td><%= area.location_id %></td>
        <td><%= link_to 'Show', area %></td>
        <td><%= link_to 'Edit', edit_area_path(area) %></td>
        <td><%= link_to 'Destroy', area, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Area', new_area_path %>

app/views/areas/new.html.erb
<style type="text/css">

.remedy{
  text-align: center;
  font-weight: 700;
  margin-bottom: 15px;
  font-family: 'Raleway', sans-serif;
}

</style>

<br>
<br>

<h1 class="remedy">New Area</h1>
<% if current_user.admin? %>
<%= render 'form', area: @area %>

<div class="container">
	<div class="col-lg-12">
		<h1>Areas</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @areas  %> 
  </tbody>
</table>
	</div>
</div>
<br>
<br>
<br>
<% else %>
<h4 style="text-align: center;"> User Not Authorized to take this action. </h4>
<% end %>

app/views/areas/show.html.erb
<br>
<br>
<br>
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @area.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @area.location.address %>
</p>

<%= link_to 'Edit', edit_area_path(@area) %> |
<%= link_to 'Back', areas_path %>
<br>
<br>
<br>

app/views/posters/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4 col-md-offset-4 col-xs-12">

<%= form_for(poster) do |f| %>
  <% if poster.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(poster.errors.count, "error") %> prohibited this poster from being saved:</h2>

      <ul>
      <% poster.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <label>Select category:</label><br>
   <%= f.collection_select :category_ids, Category.all, :id, :name, {prompt: "Select Category"}, 
    {:required => true, class: "select", style: "width: 100%;"} %>
  </div>
   
     <div class="form-group">
      <label>Select Region:</label><br>
    <%= f.collection_select :location_ids, Location.all, :id, :address, {prompt: "Select Region"}, 
    {:required => true, class: "select", style: "width: 100%;"} %>
  </div>


 <div class="form-group">
      <label>Select District:</label><br>
  <%= f.grouped_collection_select :area_ids, Location.order(:address), :areas, :address, :id, :name,  
options = {}, html_options = {:class => "select", style: "width: 100%;"} %>
   </div>

    
     <div class="form-group">
   <label>Company Name</label>
    <%= f.text_field :title, :class => "form-control", :placeholder => "Company name" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, :class => "form-control", :rows => "5", :placeholder => "What do you do?" %>
  </div>

  <div class="form-group">
    <%= f.label :price %>
    <%= f.number_field :price, :class => "form-control", :placeholder => "Price" %>
  </div>

  <div class="form-group">
    <%= f.label :negotiate %>
    <%= f.check_box :negotiate %>
  </div>

    <div class="form-group">
    <%= f.fields_for :photos, @poster.photos do |f_photo| %>
      <%= f_photo.label :image, :class => 'col-sm-2 control-label' do %>
        Photos
      <% end %>
      <div class="col-sm-10">
        <%= f_photo.file_field :image, multiple: true, :name=>'poster[photos_attributes][][posterimage]', :class => 'form-control' %>
      </div>
    <% end %>
  </div>
<br>
<br>
<br>

<h4><strong>Additional contact details</strong></h4>
<div style="background-color: white; border-radius: 10px; padding: 20px;">
<div class="form-group">
    <label>Company Name</label>
    <%= f.text_field :company, :class => "form-control", :placeholder => "Company Name" %>
  </div>

  <div class="form-group">
    <label>Location</label>
    <%= f.text_field :place, :class => "form-control", :placeholder => "Company Location" %>
  </div>

<div class="form-group">
    <label>Phone Number (1)</label>
    <%= f.text_field :phone1, :class => "form-control", :placeholder => "Phone number 1" %>
  </div>

<div class="form-group">
    <label>Phone number (2)</label>
    <%= f.text_field :phone2, :class => "form-control", :placeholder => "Phone number 2" %>
  </div>

</div>

  <div class="form-group" style="margin-top: 20px;">
    <%= f.submit "Submit for review", :class => "btn btn-lg btn-default pull-right" %>
  </div>
<% end %>

</div>
</div>
</div>
<br>
<br>
<br>


<script type="text/javascript">

$( document ).ready(function() {
 $('.select').select2();
});


</script>

<script>
jQuery(function() {
  var areas;
  areas = $('#poster_area_ids').html();
  return $('#poster_location_ids').change(function() {
    var escaped_location, options, location;
    location = $('#poster_location_ids :selected').text();
    escaped_location = location.replace(/([ #;&,.+*~\':"!^$[\]()=>|\/@])/g, '\\$1');
    options = $(areas).filter("optgroup[label='" + escaped_location + "']").html();
    if (options) {
      $('#poster_area_ids').html(options);
      return $('#poster_area_ids').parent().show();
    } else {
      $('#poster_area_ids').empty();
      
    }
  });
});
</script>

app/views/posters/_poster.html.erb
  <style type="text/css">

   .thumbnail{
    height: 350px;
   }

   @media only screen and (max-width : 992px) {

 .thumbnail{
    height: auto;
   }

    }

  </style>

  <div class="col-sm-4 col-lg-4 col-md-4">
                        <div class="thumbnail">
                          <% if signed_in? %>
                          <p class="pull-right">
                                <%= link_to 'Favourite', favorite_poster_path(poster), method: :post, :class => "btn btn-info", :style => "margin-top: 10px; margin-right: 10px;" %>
                              </p>
                          <% else %>
                          <p class="pull-right">
                            <a href="/users/sign_in" class="btn btn-info" style="margin-top: 10px; margin-right: 10px;">Favourite</a>
                              </p>
                          <% end %>
                            <br>
                            <% if poster.photos.present? %>
                            <img src="<%= poster.photos.first.posterimage_url(:partialimage) %>" alt="">
                            <% else %>
                             <img src="nopipartial.jpg" alt="">
                            <% end %>
                            <div class="caption">
                              <% if poster.price.present? %>
                                <h5 class="pull-right"><strong><span style="font-size: 9px;">GHC</span> <%= poster.price %></strong>
                                  </h5>
                                  <% end %>
                                  <% if poster.title.present? %>
                                <h4><span style=""><%= link_to truncate( poster.title, :length => 21), poster, :style => "color: #e20d0d; font-weight: 700; font-size: 13px;" %></span>
                                </h4>
                                <% end %>
                                <% if poster.description.present? %>
                                <p><%= truncate( poster.description , :length => 50)  %></p>
                                <% end %>
                            </div>
                            <div class="ratings">
                                <p class="pull-right"><%= poster.comments.count %> coments</p>
                                <p>
                                    <span style="color: #999999; font-weight: 500; font-size: 11px;"><%= time_ago_in_words(poster.created_at) %> ago</span>
                                </p>
                                <p>
                                  <% if signed_in? %>
                                <% if current_user.admin? || poster.user == current_user %>
                                <%= link_to 'delete ad', poster, method: :delete, data: { confirm: 'Are you sure?' } %> |  <%= link_to 'edit ad', edit_poster_path(poster) %> |
                                <% end %> 
                                <% if poster.approved? %>
                                <strong> Approved</strong>
                                <% else %>
                                <strong> Unaproved</strong>
                                <% end %>
                                <% end %>
                              </p>
                            </div>
                        </div>
                    </div>

app/views/posters/edit.html.erb
<style type="text/css">

.remedy{
  text-align: center;
  font-weight: 700;
  margin-bottom: 15px;
  font-family: 'Raleway', sans-serif;
}

</style>

<br>
<br>
<br>
<h1 class="remedy">Edit Poster</h1>

<%= render 'form', poster: @poster %>

app/views/posters/index.html.erb
<title>BoomGh | Businesses and More</title>

<meta name="description" content="Boom Gh is a website that helps buyers find local businesses and local businesses find customers">
      <meta name="keywords" content="Local businesses, Buyers, Classfields, Buy online, Sell online, Accra, Ghana">
      <meta name="author" content="Bernard Lomo">
      <meta property="og:title" content="BoomGh | Businesses and More">
      <meta property="og:description" content="Boom Gh is a website that helps buyers find local businesses and local businesses find customers">


<style type="text/css">
body {
    padding-top: 70px; /* Required padding for .navbar-fixed-top. Remove if using .navbar-static-top. Change if height of navigation changes. */
}

.adiself{
    background-color: #fff;
    padding-top: 10px;
    padding-bottom: 10px;
    padding-right: 15px;
    padding-left: 15px;
    border-radius: 5px;
    position: relative;
    left: 25px;
    border: 0.5px solid #b2b2b2;
    border-bottom: 2px solid #b2b2b2;
}

.adisab{
    position: relative;
    left: -45px;
}

.adiselfr{
    background-color: #fff;
    padding-top: 12px;
    padding-bottom: 12px;
    padding-right: 0px;
    padding-left: 0px;
    border-radius: 5px;
    border: 0.5px solid #b2b2b2;
    border-bottom: 2px solid #b2b2b2;
}

.adiselfer{
    background-color: #fff;
    padding-top: 10px;
    padding-bottom: 10px;
    padding-right: 10px;
    padding-left: 10px;
    border-radius: 5px;
    border: 0.5px solid #b2b2b2;
    border-bottom: 2px solid #b2b2b2;
}

.slide-image {
    width: 100%;
}

.carousel-holder {
    margin-bottom: 30px;
}

.carousel-control,
.item {
    border-radius: 4px;
}

.caption {
    height: 130px;
    overflow: hidden;
}

.caption h4 {
    white-space: nowrap;
}

.thumbnail img {
    width: 100%;
}

.ratings {
    padding-right: 10px;
    padding-left: 10px;
    color: #d17581;
}

.thumbnail {
    padding: 0;
}

.thumbnail .caption-full {
    padding: 9px;
    color: #333;
}

.mobile-form{
    display: none;
}

footer {
    margin: 50px 0;
}

 @media only screen and (max-width : 992px) {

    .adiself{
    background-color: #fff;
    padding-top: 10px;
    padding-bottom: 10px;
    padding-right: 15px;
    padding-left: 15px;
    border-radius: 5px;
    position: relative;
    left: 0px;
    border: 0.5px solid #b2b2b2;
    border-bottom: 2px solid #b2b2b2;
    margin-bottom: 20px;
}

.adisab{
    position: relative;
    left: 0px;
}

.mobile-form{
    display: inline;
}
      
    }

     @media (min-width: 768px) {
  .hidden-md-up {
    display: none !important;
  }
}

        @media only screen and (min-width : 100px) and (max-width : 600px) {

         .hide-on-mobile{
          display: none;
         }
     }

</style>




 

    <!-- Page Content -->
    <div class="container">

        <div class="row">

            <div class="col-md-3 adiself hide-on-mobile">
    <div class="mobile-form">
    <%= form_tag search_path , method: :get, :class => "navbar-form navbar-right" do %>
        <div class="form-group">
           <%= text_field_tag :q, nil , :placeholder => "Search for items", :class => "form-control"%>
        </div>
        <button type="submit" class="btn btn-default" style="color: #fff; background-color: #000; border: 1px solid #fff;">Search</button>
      <% end %>
      <hr>
  </div>
                <p class="lead"><strong>All categories</strong></p>
                <div class="list-group">
                    <%= render @categories %>
                </div>
                <p class="lead"><strong>All of Ghana</strong></p>
                <div class="list-group">
                    <%= render @locations %>
                </div>
            </div>

            <div class="col-sm-12 adiself hidden-md-up" style="margin-top: 0px;">
    <div class="mobile-form">
    <%= form_tag search_path , method: :get, :class => "navbar-form navbar-right" do %>
        <div class="form-group">
           <%= text_field_tag :q, nil , :placeholder => "Search for items", :class => "form-control"%>
        </div>
         <button type="submit" class="btn btn-default" style="color: #fff; background-color: #000; border: 1px solid #fff;">Search</button>
      <% end %>
  </div>
    </div>

            <div class="col-md-8 col-md-offset-1 adisab col-sm-12">

                <div class="row carousel-holder adiselfr">

                    <div class="col-md-12">
                        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                            <ol class="carousel-indicators">
                                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                            </ol>
                            <div class="carousel-inner">
                                <div class="item active">
                                    <img class="slide-image" src="c1.jpg" alt="">
                                </div>
                                <div class="item">
                                    <img class="slide-image" src="c2.jpg" alt="">
                                </div>
                                <div class="item">
                                    <img class="slide-image" src="c3.jpg" alt="">
                                </div>
                            </div>
                            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                                <span class="glyphicon glyphicon-chevron-right"></span>
                            </a>
                            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                                <span class="glyphicon glyphicon-chevron-right"></span>
                            </a>
                        </div>
                    </div>



                </div>

                <div class="row adiselfer">

                 <%= render @posters %> 

                </div>

                <div class="row">

                <div class="col-md-3 adiself hidden-md-up" style="margin-top: 20px;">
    <div class="mobile-form">
    <%= form_tag search_path , method: :get, :class => "navbar-form navbar-right" do %>
        <div class="form-group">
           <%= text_field_tag :q, nil , :placeholder => "Search for items", :class => "form-control"%>
        </div>
        <button type="submit" class="btn btn-default" style="color: #fff; background-color: #000; border: 1px solid #fff;">Search</button>
      <% end %>
      <hr>
  </div>
                <p class="lead"><strong>All categories</strong></p>
                <div class="list-group">
                    <%= render @categories %>
                </div>
                <p class="lead"><strong>All of Ghana</strong></p>
                <div class="list-group">
                    <%= render @locations %>
                </div>
            </div>

                </div>


            </div>

        </div>

    </div>
    <!-- /.container -->

    <div class="container">

       
     

    </div>
    <!-- /.container -->

app/views/posters/new.html.erb
<style type="text/css">

.remedy{
  text-align: center;
  font-weight: 700;
  margin-bottom: 15px;
  font-family: 'Raleway', sans-serif;
}

</style>

<br>
<br>
<br>
<h1 class="remedy">POST HERE!</h1>

<%= render 'form', poster: @poster %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Already have and account, Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Don't have an accoutn yet, Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<br>
<br>
<br>
<h4 style="text-align: center;"><strong><%= @user.email %></strong></h4>
<br>
<h2 style="text-align: center;">My Ads</h2>
<div class="container">
	<div class="row">
		 <%= render @posters %> 
	</div>
	</div>

<h2 style="text-align: center;">Favorite Ads</h2>
<div class="container">
	<div class="row">
		 <%= render @favorites %> 
	</div>
	</div>